### ISSUE TITLE
Basic Authentication and/or Mutual TLS

### ISSUE THREAD

**Issue by rlees85** [xente/loki-logger-handler#11]
Currently there is no way to do authentication and this looks like the last standing Loki package for Python. I think I can probably add basic auth fairly easily and may open a PR for this unless someone beats me to it.

Mutual TLS would also be nice but I am not sure that is as trivial

**Comment by xente** [comment]
Hi, 

I am able to connect and send logs without issues. 

Can you provide the error?

Are you using the the connection string like "https://USER:PASSWORD@logs-prod-eu-west-0.grafana.net/loki/api/v1/push"?

Are you generating the token (PASSWORD) using below grants?

![image](https://github.com/xente/loki-logger-handler/assets/22558685/567d2c1b-85a4-418a-a6c0-4db09cba649e)

**Comment by rlees85** [comment]
You know what I think you got a point for basic auth at least. I didn't try that, I forgot that format existed! I have noticed you can also send custom headers too (like, `Authorization`), so this might be a none-issue.

I am not using Grafana cloud, its just a self hosted Loki. Just trying to secure communications between different Kubernetes clusters, etc.

I'll close this for now, maybe I'll come back in the future if I decide I want to add mutual TLS (but I'll PR it if I do)
