### ISSUE TITLE
Handler should use self.formatter instead of self.logger_formatter

### ISSUE THREAD

**Issue by Liquidmasl** [xente/loki-logger-handler#14]
logging.Handler already has self.formatter and a setter method for it, but the setter method does nothing because the lokiLoggingHander does use its own formatter variable. 

This just lead to a lot of confusion

```py

class LokiLoggerHandler(logging.Handler):
    def __init__(
        self,
        url,
        labels,
        labelKeys=None,
        timeout=10,
        compressed=True,
        defaultFormatter=LoggerFormatter(),
        additional_headers=dict()
    ):
        super().__init__()

        if labelKeys is None:
            labelKeys = {}

        self.labels = labels
        self.labelKeys = labelKeys
        self.timeout = timeout
        self.logger_formatter = defaultFormatter  # This should be just self.formatter
        self.request = LokiRequest(url=url, compressed=compressed, additional_headers=additional_headers)
        self.buffer = queue.Queue()
        self.flush_thread = threading.Thread(target=self._flush, daemon=True)
        self.flush_thread.start()
```

just changing that one variable decleration makes it easier for the logger to be a drop in replacement for another handler

**Comment by Liquidmasl** [comment]
also when I am not mistaken formatters normally return strings.

it totally makes sense that the handler wants a dictionary, but it would be great if it would parse a json formatted string if it gets one.

This would also greatly increase the compatibility with different logging modules.

I am using structlog currently. Its ProcessorFormatter must return strings (also annoying)
So to make it compatible I have to serialize the event_dict (basically the record) to json, then write a custom formatter that first sends the record through the processorFormatter, then deserialize again to send to this handler which den serializes it again. This formatter must then be set as default_formatter to the loki handler.

thats a bit absurd haha

**Comment by Liquidmasl** [comment]
ah well, and in emit the format call should change as well of course

**Comment by Liquidmasl** [comment]
ah well, and in emit the format call should change as well of course

**Comment by xente** [comment]
Hi @Liquidmasl , total agree we will be working on it.

**Comment by xente** [comment]
Pull request #19 has been created with the fix
