### ISSUE TITLE
Add structured-metadata functionnality 

### ISSUE THREAD

**Issue by jcdauchy-moodys** [xente/loki-logger-handler#26]
In loki 2.9 and 3.x, we can now add metadata to the payload.

Here the PR which adds it to fluent-bit : https://github.com/fluent/fluent-bit/pull/9048

Would be cool to be able to define what is sent as structure metadata.

Tell me if you need more information.

**Comment by xente** [comment]
@jcdauchy-moodys feature will be merge into pull request #33

**Comment by jcdauchy-moodys** [comment]
Thanks a lot @xente , this is awesome !
